### PR TITLE
fix emoji punctuation marks

### LINKED ISSUE #2: Emoji: Punctuation marks disappear
**Bug:**
 When no emoji for the current word is found, but a punctuation mark is present, it won't appear after the text is modified. 

**Expected result:**
 It should appear in the modified text.

### PR DESCRIPTION
**Pull request by nils-keller-dev**
fixes #2

### CODE REVIEW

**Comment by StarAppeal** [comment]
Please document your tests with test results before approving the pull request.

**Comment by nils-keller-dev** [comment]
> Please document your tests with test results before approving the pull request.

Before: `'Leute🧑‍🤝‍🧑, checkt✅ das👉 mal aus rief📣 Tim`
After: `'Leute🧑‍🤝‍🧑, checkt✅🗒 das👇 mal aus', rief📣 Tim.`

File: src/generators/emoji/generator.ts [hunk 1]
```diff
@@ -118,7 +119,7 @@ function replaceNumbers(str: string) {
 
 function removePunctuations(str: string): EmojiString {
   const lowerStr = str.toLowerCase();
-  if (!/[,|.|!|?|;|(|)|"]/g.test(str)) {
+  if (!/[,|.|!|?|;|(|)|"|'|:]/g.test(str)) {
     return {
```
Comment (StarAppeal) [inline src/generators/emoji/generator.ts:123]: bitte unleserlicher

File: src/generators/emoji/generator.ts [hunk 2]
```diff
@@ -127,8 +128,8 @@ function removePunctuations(str: string): EmojiString {
   }
 
   return {
-    strippedString: lowerStr.replace(/[,|.|!|?|;|(|)|"]/g, ""),
+    strippedString: lowerStr.replace(/[,|.|!|?|;|(|)|"|'|:]/g, ""),
     originalString: str,
-    emojiIndex: /[,|.|!|?|;|(|)|"]*$/.exec(str).index,
+    emojiIndex: /[,|.|!|?|;|(|)|"|'|:]*$/.exec(str).index,
```
Comment (StarAppeal) [inline src/generators/emoji/generator.ts:133]: s.o.

File: src/generators/emoji/generator.ts (hunk 1 above)
Comment (StarAppeal) [reply src/generators/emoji/generator.ts:123]: Ne ernsthaft, könntest du das irgendwie auslagern, in eine Methode oder so um zu beschreiben was dieses RegEx macht? RegEx schreiben ist einfacher als bestehende zu lesen.

File: src/generators/emoji/generator.ts [hunk 3]
```diff
@@ -118,7 +119,7 @@ function replaceNumbers(str: string) {
 
 function removePunctuations(str: string): EmojiString {
   const lowerStr = str.toLowerCase();
-  if (!/[,|.|!|?|;|(|)|"]/g.test(str)) {
+  if (!/[,|.|!|?|;|(|)|"|'|:]/g.test(str)) {
```
Comment (StarAppeal) [inline src/generators/emoji/generator.ts]: Could you please extract it to somewhere else, like a method or so, so it has a readable name? Writing regex is always easier than reading it, this would improve readability by a lot.

**Review by StarAppeal — CHANGES_REQUESTED** [review]
Improve readabilityx from regex

File: src/generators/emoji/generator.ts (hunk 3 above)
Comment (nils-keller-dev) [reply src/generators/emoji/generator.ts]: done

**Review by StarAppeal — APPROVED** [review]
Looks good now!
